# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 478db93abf4f9e2ed8eb7d796a2525def42ce7b035746a19e6637d6cdf8aa155c6c973a3f500450ae04a7bb53ba3e9b9f8fb82cc49d2924d17ad2307ce5168a1

test:
  secret_key_base: 1bb1d18145cc9362d4e0981ce8b6b6104b8110623cb4efab844de342999f2782c663c2976d6038bb3a6e1e6274ba6d0ac31fac107efa360037efb330d1a0b8bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
